name: 'Unity Pack'
description: 'Create an Unity Package from directory'
inputs:
  package-dir:
    description: 'directory path of unity package relative to unity project directory'
    required: true
  project-dir:
    description: 'directory of unity project'
    required: false
  output-path:
    description: 'path of .unitypackage file'
    required: false
    default: 'output.unitypackage'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package-dir }}
    - ${{ inputs.output-path }}
    - ${{ inputs.project-dir }}
branding:
  icon: 'package'
  color: 'gray-dark'
